name: test

on:
  push:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-without-mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Authenticate to Docker Hardened Image Registry
        uses: docker/login-action@v3
        with:
          registry: dhi.io
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}
      - name: Docker Meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Setup buildx
        uses: docker/setup-buildx-action@v3
      - name: Run DHI Image
        run: |
          docker buildx inspect
          docker run --rm dhi.io/python:3.13 python -c "print('Hello from DHI')"
      - name: Build with buildx targeting builder stage
        continue-on-error: true
        run: |
          docker buildx build \
            --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:test \
            --load \
            --target=builder \
            .
      - name: Build with buildx overriding image and targeting aot-cache-training-runner stage
        continue-on-error: true
        run: |
          docker buildx build \
            --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:test \
            --load \
            --build-arg AOT_CACHE_TRAINING_RUNNER_IMAGE=debian:trixie-slim \
            --target=aot-cache-training-runner \
            .
      - name: Build with buildx targeting aot-cache-training-runner stage
        continue-on-error: true
        run: |
          docker buildx build \
            --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:test \
            --load \
            --target=aot-cache-training-runner \
            .
      - name: Build and Load Image
        id: build
        uses: docker/build-push-action@v6
        with:
          load: true
          push: false
  build-with-mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Authenticate to Docker Hardened Image Registry
        uses: docker/login-action@v3
        with:
          registry: dhi.io
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}
      - name: Docker Meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Setup buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-config-inline: |
            [registry."dhi.io"]
              mirrors = ["dhi.io"]
      - name: Run DHI Image
        run: |
          docker buildx inspect
          docker run --rm dhi.io/python:3.13 python -c "print('Hello from DHI')"
      - name: Build with buildx directly
        run: |
          docker buildx build \
            --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:test \
            --load \
            .
      - name: Build and Load Image
        id: build
        uses: docker/build-push-action@v6
        with:
          load: true
          push: false
